Creating CRUD of products. added new file structure with right naming…
StupidDevJs/AtilogTask-API pull request #1
Opened 2020-09-02 17:15 UTC by StupidDevJs

… of routes ,products.controllers and other. added new dependencies,end endpoints

2020-09-04 03:54 UTC, Lionkka commented on .idea/codeStyles/codeStyleConfig.xml
> +  <state>
Надо удалить из комита все файлы идеи. Я вижу что ты уже добавил в гит игнор их. Но надо еще и из комита убрать

2020-09-04 03:54 UTC, Lionkka commented on app.js
> +app.listen(8000, () => console.log('server started'));
так как функционирование твоего АПИ не имеет смысл без бд, то сервер лучше запускать только при успешном подключении к бд

2020-09-04 03:54 UTC, Lionkka commented on app.js
> +mongoose.connect(
ты еще не дошел до пункта когда подключение надо вынести в отдельный файл? если нет, то потом сделаешь, если да или там вообще про это не написано, то вынеси подключение бд в отдельный файл

2020-09-04 03:54 UTC, Lionkka commented on controllers/goods.js
> +      res.status(500).json({ message: err.message });
используй глобальный эррор хендлер. https://expressjs.com/ru/guide/error-handling.html

2020-09-04 03:54 UTC, Lionkka commented on controllers/goods.js
> +    const { id } = req.params;
сделал деструктуризацию, а в иф используешь все равно без

2020-09-04 03:54 UTC, Lionkka commented on controllers/goods.js
> +        return res.json(product);
ретерн тут не нужен

2020-09-04 03:54 UTC, Lionkka commented on controllers/goods.js
> +      name: req.body.name,
используй деструктуризацию

2020-09-04 03:54 UTC, Lionkka commented on controllers/goods.js
> +      const newProduct = await product.save();
тут должен быть только вызов сервисов, никакой логики. У тебя тут логика это содал продукт, сделал сейв. но в контроллеры ты должен только вызывать сервисы, например saveProduct

2020-09-04 03:54 UTC, Lionkka commented on controllers/goods.js
> +      res.status(201).json(newProduct);
почему 201? почитай пожалуйста его определение внимательно. Оно говорит о том что ээто ОК без боди. а у тебя боди есть. либо убери боди, либо поменяй код

2020-09-04 03:54 UTC, Lionkka commented on controllers/goods.js
> +      const editedProduct = await Product.findOneAndUpdate(
тоеж самое, перенести в сервисы все

2020-09-04 03:54 UTC, Lionkka commented on controllers/goods.js
> +      res.status(600).json({ message: err.message });
600??

2020-09-04 03:54 UTC, Lionkka commented on routes/goods.js
> +router.get(
1. это можно чейнить
2ю зачем разделять это аж на 3 строки? красивее и удобнее будет читать такое в 1 строку

2020-09-04 03:54 UTC, Lionkka commented on mongo.js
> +const mongoose = require('mongoose');
это какой то тестовый файл? почему он в комите?

2020-09-04 11:47 UTC, StupidDevJs commented on controllers/goods.js
> +      res.status(600).json({ message: err.message });
бес попутал)))

2020-09-05 09:59 UTC, Randan requested changes
Более точечно написал в самих файлах комменты.

Здесь напишу общие рекомендации к чистоте кода
- поубирай trailing spaces.
- поубирай пустые строки, оставляй пустые строки только когда они отделяют куски кода по смыслу
- отступы между элементами в объектах, да и вообще любых элементах, перечисляемых запятыми

2020-09-05 09:59 UTC, Randan commented on .env
> +SERVER_PORT=8000
этот файл не должен попасть в репозиторий.
добавь его в гитигнор и удали отсюда.
его смысл в принципе в том, чтоб не хранить подобные данные в репозитории

2020-09-05 09:59 UTC, Randan commented on app.js
> +require('dotenv').config()
наведи порадок в файлах. просто реквайры подними в верх файла, а те, что определяешь в переменные - ниже

2020-09-05 09:59 UTC, Randan commented on app.js
> +require('dotenv').config()
по такой схеме:

`require('something from packages');`
`require('something from local');`
`const thing = require('something from packages');`
`const thing2 = require('something from local');`

2020-09-05 09:59 UTC, Randan commented on .env
> +SERVER_PORT=8000
добавь сюда SERVER_URL=localhost
на случай, если код выливать на сервер с локалки - придется переменные поменять в одном файле, а не везде по коду

2020-09-05 09:59 UTC, Randan commented on app.js
> +        origin: ["http://localhost:8000"],
используй переменные из .env

2020-09-05 09:59 UTC, Randan commented on app.js
> +    app.listen(process.env.SERVER_PORT)
сделай в верху 
const serverPort = process.env.SERVER_PORT;
и далее обращайся в этой переменной. нет смысла в .env стучаться по 1000 раз

2020-09-05 09:59 UTC, Randan commented on app.js
> +    console.log(`App started on port 8000 + mongod`)
ну и раз уж на то пошло, то `App started on port ${serverPort} + mongod` исходя из коммента выше

2020-09-05 09:59 UTC, Randan commented on app.js
> +    .on('error', () => console.log('zalupa'))
залупа тут ни к чему, внимательнее пожалуйста))

2020-09-05 09:59 UTC, Randan commented on controllers/goods.js
> +    const {name, isAvailable, price} = req.body
давай сразу привыкать, что объекты (в том числе и деструктуризация) пишутся с пробелами `{ thing1, thing2 }`, а пропсы пишутся без пробелов `{prop}`

2020-09-05 09:59 UTC, Randan commented on controllers/goods.js
> +  put: async (req, res,next) => {
деструктуризируй `req`

2020-09-05 09:59 UTC, Randan commented on controllers/goods.js
> +  delete: async (req, res,next) => {
тоже самое

2020-09-05 09:59 UTC, Randan commented on nodemon.json
> +{
добавь этот файл в гитигнор и удали из репа

2020-09-05 09:59 UTC, Randan commented on package-lock.json
>    "lockfileVersion": 1,
добавь этот файл в гитигнор и удали из репа

2020-09-05 09:59 UTC, Randan commented on package.json
> +    "server": "npx nodemon app.js"
не надо `npx`
вместо `"server": "npx nodemon app.js"`
используй
```
"start": "node app.js",
"devstart": "nodemon app.js"
```

и далее запускай
`npm run devstart` или `yarn devstart` локально
`npm run start` или `yarn start` на сервере

2020-09-05 09:59 UTC, Randan commented on services/products.js
> +const getProductById = (id) => Product.findById(id);
чисто для ознакомления. когда пробрасываешь один параметр, то скобки можно не писать))
`const getProductById = id => Product.findById(id);` можно так

2020-09-07 08:59 UTC, Randan requested changes
три коммента оставил

2020-09-07 08:59 UTC, Randan commented on mongo.js
> +    mongoose.connect(process.env.DB_HOST, options)
`process.env.DB_HOST` суй в переменные в начале файла. наслучай если ты будешь несколько раз обращаться к переменной.

2020-09-07 08:59 UTC, Randan commented on routes/goods.js
> +router.get('/products', goodsController.get);
отделяй смыслово пустой строкой блоки кода
к примеру тут после 2 и 8 строки оставь пустые. проще ж читать код потом

2020-09-07 08:59 UTC, Randan commented on routes/goods.js
> +router.get('/products', goodsController.get);
и пройдись по всем файлам, сделай то же самое

2020-09-09 14:24 UTC, Randan requested changes
там один коммент, исправь и пингани меня, заапрувлю

2020-09-09 14:24 UTC, Randan commented on app.js
> +    origin: [`http://${serverUrl}:3000`],
`${serverPort}`

2020-09-09 14:53 UTC, Randan approved these changes

2020-09-09 14:54 UTC, merged